name: autoparnet_cotiza
description: Rastreador de Refacciones Automotrices.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  async: ^2.8.2
  breakpoint: ^1.2.0
  cached_network_image: ^3.2.1
  camera: ^0.9.7+1
  connectivity_plus: ^2.3.2
  cron: ^0.5.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.1
  extended_image: ^6.2.1
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  flutter_dropzone: ^3.0.5
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.2
  flutter_ringtone_player: ^3.2.0
  flutter_svg: ^1.1.0
  flutter_typeahead: ^4.0.0
  get_it: ^7.2.0
  go_router: ^3.1.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  http_parser: ^4.0.1
  image: ^3.2.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  native_device_orientation: ^1.1.2
  path_provider: ^2.0.10
  photo_view: ^0.14.0
  provider: ^6.0.3
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.0.17

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
