// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn83mT0cki3zzeVN2maZUBukrPotp5yzQ',
    appId: '1:788916468765:web:0c87b98b4387a6e4d7daf4',
    messagingSenderId: '788916468765',
    projectId: 'cotiza-28808',
    authDomain: 'cotiza-28808.firebaseapp.com',
    storageBucket: 'cotiza-28808.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmQBPIqCGiGEIGa4sGJQMmVf2fwPDbsU',
    appId: '1:788916468765:android:144f2d05d35bb310d7daf4',
    messagingSenderId: '788916468765',
    projectId: 'cotiza-28808',
    storageBucket: 'cotiza-28808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2e5PaxOElVE8Clpcys8el5V7vb14_2I',
    appId: '1:788916468765:ios:c4a8ce177f0e4a1ed7daf4',
    messagingSenderId: '788916468765',
    projectId: 'cotiza-28808',
    storageBucket: 'cotiza-28808.appspot.com',
    androidClientId: '788916468765-638p0741ad8gu88hn45epbhmsmf8ac6q.apps.googleusercontent.com',
    iosClientId: '788916468765-g9gvi1klupak6hqp870smap8vp954du2.apps.googleusercontent.com',
    iosBundleId: 'com.autoparnet.cotiza',
  );
}
