// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9t937zCgp2hEua35sVTokZ_R5PQPn2nQ',
    appId: '1:733608066006:web:d8c66408369eeaa12dc277',
    messagingSenderId: '733608066006',
    projectId: 'cotiza-13776',
    authDomain: 'cotiza-13776.firebaseapp.com',
    storageBucket: 'cotiza-13776.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3cGJCdT12nahRFEpzgPpRMpMZKD5Lt1A',
    appId: '1:733608066006:android:07a4d5fa8254a23e2dc277',
    messagingSenderId: '733608066006',
    projectId: 'cotiza-13776',
    storageBucket: 'cotiza-13776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiyemD7vo7nX_SRVxWbLrIp8AJ8qwNnxk',
    appId: '1:733608066006:ios:1bb5987ef08e3f782dc277',
    messagingSenderId: '733608066006',
    projectId: 'cotiza-13776',
    storageBucket: 'cotiza-13776.appspot.com',
    androidClientId: '733608066006-be8o88qju60us98b4j2vi90oagd5u18u.apps.googleusercontent.com',
    iosClientId: '733608066006-iff55g5djo23lniokrha5ln0l7k7nlub.apps.googleusercontent.com',
    iosBundleId: 'com.autoparnet.cotiza',
  );
}
